cop <-
function(x,y,signif.in,signif.out,H,my.range){
        y=as.numeric(y);x=as.matrix(x);
        n=nrow(x);p=ncol(x);
        lambda<-list()          
        step0<-starting(x,y,H)
	  lambda[[1]]<-list()
	  lambda[[1]][1]<-step0$lambda0	
	  lambda[[1]][2]<-step0$lambda
	  id0=step0$id	 
	  my.step=1			
	  dd=1
	  dimen=2		        
	  I=2
	  my.select<-list()
	  id1<-NULL
        while(dd<=dimen+1&dd<=length(id0)){
	           my.forward<-"conti"
		     my.backward<-"conti"	
                 while(my.step<=my.range&my.forward=="conti"){
                		my.idf<-forward.corp(x,y,id0,H,signif.in,dd,as.numeric(lambda[[dd]][I]))
                		stepf<-my.idf$id
                		my.stop1=my.idf$my.stop
				lambda[[dd]][I+1]=my.idf$lambda
				I=I+1
                		if(my.stop1=="stop"){
                        	id0<-stepf
					my.forward<-"stop"
                		}
				my.del<-setdiff(stepf,id1)
				while(my.forward=="conti"&my.backward=="conti"&length(my.del)!=0){
                			my.id<-backward.corp(x,y,id1,my.del,H,signif.out,dd,as.numeric(lambda[[dd]][I]))
                			stepb<-my.id$id
                			my.backward=my.id$my.stop
					lambda[[dd]][I+1]=my.id$lambda
					I=I+1
					id0=stepb
					stepf<-id0
				}
				my.backward="conti"
				my.step<-length(id0)							
			}
			x.sel.d<-x[,id0]
			my.select[[dd]]<-setdiff(id0,id1)
			id1<-id0
			my.dr<-dr(y~scale(x.sel.d),nslices=H)
			dimen.p<-dr.test(my.dr,my.range)[,3]
			dimen<-max(which(dimen.p<=0.05))
			lambda[[dd]]<-unlist(lambda[[dd]])
			dd<-dd+1
			I=1						
			lambda[[dd]]<-list()
			lambda[[dd]][1]<-my.dr$evalues[dd]      
	}
	lambda<-lambda[-dd]
	my.select<-my.select[-(dd-1)]
      return(list(id=unlist(my.select),lambda=lambda,my.sel=my.select)) 
}

